name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk-version: [1.8]
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK ${{ matrix.jdk-version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk-version }}

      - name: Gradle Cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle
          key: gradle

      - name: Maven Cache
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: m2


      - name: Build library
        run: ./gradlew build publishToMavenLocal

      - name: Build gradle plugin
        run: ./gradlew -p plugins/gradle/graphql-java-codegen-gradle-plugin build publishToMavenLocal

      - name: Build maven plugin
        working-directory: plugins/maven/graphql-java-codegen-maven-plugin
        run: mvn install



      - name: Build gradle example-server
        run: ./gradlew -p plugins/gradle/example-server test

      - name: Build gradle example-client
        run: ./gradlew -p plugins/gradle/example-client test

      - name: Build maven example-server
        working-directory: plugins/maven/example-server
        run: mvn package

      - name: Build maven example-client
        working-directory: plugins/maven/example-client
        run: mvn package

  code-coverage:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Gradle Cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle
          key: gradle

      - name: Maven Cache
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: m2

      - name: Generate code coverage report
        run: ./gradlew codeCoverageReport

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
          yml: .codecov.yml
